
/** Tempo de produto x Tempo incidentes */
CREATE OR REPLACE VIEW SUB_TEMPO_PRODUCAO_TEMPO_PRODUCAO_INCIDENTES AS
	SELECT 
		TOTAL_MINUTOS AS MINUTOS, 
		PERIODO,
		CASE 
		  WHEN TIPO = 1 THEN 1
		  WHEN TIPO = 3 THEN 1
		  WHEN TIPO = 2 THEN 2
		  WHEN TIPO = 4 THEN 2
		  WHEN TIPO = 7 THEN 2
		  END
		AS TIPO    
	FROM 
		V_FICHAS
	WHERE 
		TIPO IN (1, 2, 3, 4, 7);

CREATE OR REPLACE VIEW SUBPRODUCAO_TEMPO_PRODUCAO_TEMPO_PRODUCAO_INCIDENTES AS
	SELECT 
		FLOOR(SUM(MINUTOS) / 60) AS HORAS, 
		TIPO, 
		PERIODO 
	FROM 
		SUB_TEMPO_PRODUCAO_TEMPO_PRODUCAO_INCIDENTES
	WHERE
		TIPO = 2
	GROUP BY 
		TIPO, 
		PERIODO;

CREATE OR REPLACE VIEW SUBCORRECAO_TEMPO_PRODUCAO_TEMPO_PRODUCAO_INCIDENTES AS
	SELECT 
		FLOOR(SUM(MINUTOS) / 60) AS HORAS, 
		TIPO, 
		PERIODO 
	FROM 
		SUB_TEMPO_PRODUCAO_TEMPO_PRODUCAO_INCIDENTES
	WHERE
		TIPO = 1
	GROUP BY 
		TIPO, 
		PERIODO;      
      
CREATE OR REPLACE VIEW TEMPO_PRODUCAO_TEMPO_PRODUCAO_INCIDENTES AS
	SELECT 
		p.periodo as periodo,
        p.horas as producao,
        c.horas as incidentes
	FROM 
		SUBPRODUCAO_TEMPO_PRODUCAO_TEMPO_PRODUCAO_INCIDENTES P
	INNER JOIN 
		SUBCORRECAO_TEMPO_PRODUCAO_TEMPO_PRODUCAO_INCIDENTES C 
			ON (C.Periodo = p.Periodo)
	;

 
CREATE OR REPLACE VIEW SUBTEMPO_REVISAO AS
	SELECT 
		*,
		ROUND(REV_PROGRAMACAO / TOTPRO * 100) AS PERCENTUAL_REVISAO
	FROM 
		v_fichas
	WHERE 
		REV_PROGRAMACAO < TOTPRO AND
        HORAS_CORRECAO * 100 / TOTAL_MINUTOS < 60;
;

CREATE OR REPLACE VIEW TEMPO_REVISAO AS
	SELECT
		PERIODO AS periodo,
        Percentual_Revisao,
        CONCAT(MIN(Percentual_Revisao), ' - ', MAX(Percentual_Revisao)) AS intervalo,
        AVG(Percentual_Revisao) AS percentualRevisaoMedio,
        SUM(REV_PROGRAMACAO) AS totalRevisao,
		SUM(HORAS_CORRECAO) * 100 / SUM(TOTAL_MINUTOS) AS incidentes
	FROM
		SUBTEMPO_REVISAO
	WHERE 
		TIPO IN (5, 6, 7)
	GROUP BY 
		FLOOR(PERCENTUAL_REVISAO / 10)
	ORDER BY intervalo;
    
CREATE OR REPLACE VIEW TEMPO_MEDIO_REVISAO AS
	SELECT
		PERIODO AS periodo,
		Percentual_Revisao,
		CONCAT(MIN(Percentual_Revisao), ' - ', MAX(Percentual_Revisao)) AS intervalo,		
		SUM(TOTAL_MINUTOS) * 100 / (SELECT SUM(TOTAL_MINUTOS) FROM SUBTEMPO_REVISAO WHERE TIPO IN (5, 6, 7)) AS percentualProducao
	FROM
		SUBTEMPO_REVISAO
	WHERE 
		TIPO IN (5, 6, 7)
	GROUP BY 
		FLOOR(PERCENTUAL_REVISAO / 10)
	ORDER BY intervalo;

CREATE OR REPLACE VIEW TEMPO_MEDIO_REVISAO_CORRECAO AS
	SELECT
		PERIODO AS periodo,
		Percentual_Revisao,
		CONCAT(MIN(Percentual_Revisao), ' - ', MAX(Percentual_Revisao)) AS intervalo,		
		SUM(HORAS_CORRECAO),
        SUM(HORAS_CORRECAO) / 60 AS TOT_HOR,
        SUM(TOTAL_MINUTOS) TOT,
        SUM(REV_PROGRAMACAO) TOT_REV
	FROM
		SUBTEMPO_REVISAO
	WHERE 
		TIPO IN (5, 6, 7)
	GROUP BY 
		FLOOR(PERCENTUAL_REVISAO / 10)
	ORDER BY intervalo;


CREATE OR REPLACE VIEW INFORMACAO_PERIODO AS
	SELECT 
		Periodo AS periodo,
		COUNT(*) AS numeroProducao,
		SUM(NUMERO_ERROS) AS numeroIncidentes,
		SUM(TOTPRO) AS totalImplementacaoMinutos,
		SUM(REV_PROGRAMACAO) AS totalRevicaoMinutos,
		SUM(TOTAL_MINUTOS) AS totalProducaoHorasMinutos,
        SUM(TOTAL_MINUTOS) / 60 AS totalProducaoHoras,
		SUM(HORAS_CORRECAO)  / 60 AS totalIncidentesHoras,
		(SUM(TOTAL_MINUTOS) / 60) / COUNT(*) AS mediaProducao,
		(SUM(HORAS_CORRECAO)  / 60) / SUM(NUMERO_ERROS) AS mediaIncidentes
	FROM 
		v_fichas
	WHERE
		TIPO IN (5, 6, 7) AND
		REV_PROGRAMACAO < TOTPRO AND
        HORAS_CORRECAO * 100 / TOTAL_MINUTOS < 60;


SELECT * FROM INFORMACAO_PERIODO;

SELECT sum(TOT)FROM TEMPO_MEDIO_REVISAO_CORRECAO;


SELECT * FROM TEMPO_REVISAO;
SELECT * FROM TEMPO_MEDIO_REVISAO_CORRECAO;


SELECT
		PERIODO AS periodo,
        Percentual_Revisao,
        CONCAT(MIN(Percentual_Revisao), ' - ', MAX(Percentual_Revisao)) AS intervalo,
		SUM(HORAS_CORRECAO) * 100 / SUM(TOTAL_MINUTOS) AS incidentes,
        COUNT(*)
	FROM
		SUBTEMPO_REVISAO
	WHERE 
		TIPO IN (5,6,7)
	GROUP BY 
		FLOOR(PERCENTUAL_REVISAO / 10)
	ORDER BY intervalo;
    

SELECT *, HORAS_CORRECAO * 100 / TOTAL_MINUTOS AS T FROM SUBTEMPO_REVISAO

WHERE Percentual_Revisao > 60 AND Percentual_Revisao < 70 AND HORAS_CORRECAO > 0

ORDER BY T DESC
;

SELECT * FROM TEMPO_MEDIO_PRODUCAO;



SELECT SUM(REV_PROGRAMACAO) FROM v_fichas WHERE TIPO IN (5, 6, 7);


SELECT
	PERIODO AS periodo,
	Percentual_Revisao,
	CONCAT(MIN(Percentual_Revisao), ' - ', MAX(Percentual_Revisao)) AS intervalo,
	SUM(HORAS_CORRECAO)
FROM
	SUBTEMPO_REVISAO
WHERE 
	TIPO IN (5, 6, 7)
GROUP BY 
	FLOOR(PERCENTUAL_REVISAO / 10)
ORDER BY intervalo;


	SELECT
		PERIODO AS periodo,
        Percentual_Revisao,
        CONCAT(MIN(Percentual_Revisao), ' - ', MAX(Percentual_Revisao)) AS intervalo,
		SUM(HORAS_CORRECAO) * 100 / SUM(TOTAL_MINUTOS) AS incidentes
	FROM
		SUBTEMPO_REVISAO
	WHERE 
		TIPO IN (5, 6, 7)
	ORDER BY intervalo;
